/* The following code was generated by JFlex 1.6.1 */

package parser;

import java_cup.runtime.Symbol;
import java.util.*;
import java.io.*;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.6.1
 * from the specification file <tt>C:/Users/Usuario/Documents/Compiladores/while_ut1/lexer.jflex</tt>
 */
class Lexer implements java_cup.runtime.Scanner, sym {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\43\1\41\1\46\1\43\1\43\22\0\1\43\1\1\1\40"+
    "\3\0\1\2\1\0\1\3\1\4\1\20\1\21\1\0\1\22\1\0"+
    "\1\45\12\36\1\0\1\23\1\24\1\25\3\0\32\37\1\0\1\42"+
    "\2\0\1\37\1\0\1\30\2\37\1\16\1\13\1\17\1\14\1\15"+
    "\1\7\1\37\1\31\1\12\1\37\1\10\1\26\1\5\1\37\1\6"+
    "\1\27\1\11\1\32\1\44\1\33\3\37\1\34\1\0\1\35\7\0"+
    "\1\46\u1fa2\0\1\46\1\46\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\udfe6\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\1\1\3\1\4\10\5\1\6"+
    "\1\7\1\10\1\11\1\1\1\12\2\5\1\13\1\14"+
    "\1\15\1\1\1\16\1\5\1\1\1\17\1\5\1\20"+
    "\5\5\1\21\1\5\1\22\1\23\2\5\1\0\1\24"+
    "\3\0\11\5\2\0\1\16\1\5\1\25\1\26\1\5"+
    "\1\27\2\5\1\30\1\5\1\0\1\16\1\31\2\5"+
    "\1\32\1\33\1\34\1\5\1\35";

  private static int [] zzUnpackAction() {
    int [] result = new int[79];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\47\0\47\0\116\0\47\0\47\0\165\0\234"+
    "\0\303\0\352\0\u0111\0\u0138\0\u015f\0\u0186\0\47\0\47"+
    "\0\47\0\47\0\u01ad\0\u01d4\0\u01fb\0\u0222\0\47\0\47"+
    "\0\u0249\0\u0270\0\u0297\0\u02be\0\u02e5\0\47\0\u030c\0\234"+
    "\0\u0333\0\u035a\0\u0381\0\u03a8\0\u03cf\0\234\0\u03f6\0\47"+
    "\0\47\0\u041d\0\u0444\0\u0270\0\47\0\u046b\0\u0492\0\u04b9"+
    "\0\u04e0\0\u0507\0\u052e\0\u0555\0\u057c\0\u05a3\0\u05ca\0\u05f1"+
    "\0\u0618\0\u063f\0\u0666\0\47\0\u068d\0\234\0\234\0\u06b4"+
    "\0\234\0\u06db\0\u0702\0\234\0\u0729\0\u0750\0\u063f\0\234"+
    "\0\u0777\0\u079e\0\234\0\234\0\234\0\u07c5\0\234";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[79];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\6\1\7\1\10\1\11"+
    "\1\10\1\12\1\13\1\14\2\10\1\15\1\16\1\17"+
    "\1\20\1\21\1\22\1\23\1\24\1\10\1\25\3\10"+
    "\1\26\1\27\1\30\1\31\1\10\1\32\1\33\1\2"+
    "\1\33\1\34\1\35\52\0\1\36\51\0\1\10\1\37"+
    "\11\10\6\0\6\10\2\0\2\10\4\0\1\10\7\0"+
    "\13\10\6\0\6\10\2\0\2\10\4\0\1\10\7\0"+
    "\12\10\1\40\6\0\6\10\2\0\2\10\4\0\1\10"+
    "\7\0\1\10\1\41\6\10\1\42\2\10\6\0\6\10"+
    "\2\0\2\10\4\0\1\10\7\0\6\10\1\43\4\10"+
    "\6\0\6\10\2\0\2\10\4\0\1\10\7\0\5\10"+
    "\1\44\5\10\6\0\6\10\2\0\2\10\4\0\1\10"+
    "\7\0\6\10\1\45\4\10\6\0\1\46\5\10\2\0"+
    "\2\10\4\0\1\10\7\0\13\10\6\0\2\10\1\47"+
    "\3\10\2\0\2\10\4\0\1\10\27\0\1\50\46\0"+
    "\1\51\26\0\13\10\6\0\3\10\1\52\2\10\2\0"+
    "\2\10\4\0\1\10\7\0\10\10\1\53\2\10\6\0"+
    "\6\10\2\0\2\10\4\0\1\10\40\0\1\31\10\0"+
    "\40\54\1\55\1\0\1\56\4\54\41\0\1\33\1\0"+
    "\2\33\7\0\13\10\6\0\6\10\2\0\2\10\1\0"+
    "\1\33\1\0\1\33\1\34\22\0\1\57\24\0\1\60"+
    "\6\0\2\10\1\61\10\10\6\0\6\10\2\0\2\10"+
    "\4\0\1\10\7\0\13\10\6\0\4\10\1\62\1\10"+
    "\2\0\2\10\4\0\1\10\7\0\6\10\1\63\4\10"+
    "\6\0\6\10\2\0\2\10\4\0\1\10\7\0\3\10"+
    "\1\64\7\10\6\0\6\10\2\0\2\10\4\0\1\10"+
    "\7\0\13\10\6\0\1\10\1\65\4\10\2\0\2\10"+
    "\4\0\1\10\7\0\12\10\1\66\6\0\6\10\2\0"+
    "\2\10\4\0\1\10\7\0\5\10\1\67\5\10\6\0"+
    "\6\10\2\0\2\10\4\0\1\10\7\0\2\10\1\70"+
    "\10\10\6\0\6\10\2\0\2\10\4\0\1\10\7\0"+
    "\2\10\1\71\10\10\6\0\6\10\2\0\2\10\4\0"+
    "\1\10\2\0\41\54\1\0\5\54\20\72\1\73\26\72"+
    "\41\60\1\74\5\60\5\0\3\10\1\75\7\10\6\0"+
    "\6\10\2\0\2\10\4\0\1\10\7\0\6\10\1\76"+
    "\4\10\6\0\6\10\2\0\2\10\4\0\1\10\7\0"+
    "\3\10\1\77\7\10\6\0\6\10\2\0\2\10\4\0"+
    "\1\10\7\0\7\10\1\100\3\10\6\0\6\10\2\0"+
    "\2\10\4\0\1\10\7\0\6\10\1\101\4\10\6\0"+
    "\6\10\2\0\2\10\4\0\1\10\7\0\2\10\1\102"+
    "\10\10\6\0\6\10\2\0\2\10\4\0\1\10\7\0"+
    "\13\10\6\0\1\10\1\103\4\10\2\0\2\10\4\0"+
    "\1\10\7\0\1\104\12\10\6\0\6\10\2\0\2\10"+
    "\4\0\1\10\7\0\5\10\1\105\5\10\6\0\6\10"+
    "\2\0\2\10\4\0\1\10\2\0\20\72\1\106\46\72"+
    "\1\73\24\72\1\107\1\72\5\0\4\10\1\110\6\10"+
    "\6\0\6\10\2\0\2\10\4\0\1\10\7\0\4\10"+
    "\1\111\6\10\6\0\6\10\2\0\2\10\4\0\1\10"+
    "\7\0\3\10\1\112\7\10\6\0\6\10\2\0\2\10"+
    "\4\0\1\10\7\0\6\10\1\113\4\10\6\0\6\10"+
    "\2\0\2\10\4\0\1\10\7\0\6\10\1\114\4\10"+
    "\6\0\6\10\2\0\2\10\4\0\1\10\2\0\20\72"+
    "\1\73\24\72\1\74\1\72\5\0\10\10\1\115\2\10"+
    "\6\0\6\10\2\0\2\10\4\0\1\10\7\0\6\10"+
    "\1\116\4\10\6\0\6\10\2\0\2\10\4\0\1\10"+
    "\7\0\11\10\1\117\1\10\6\0\6\10\2\0\2\10"+
    "\4\0\1\10\2\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[2028];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\2\11\1\1\2\11\10\1\4\11\4\1\2\11"+
    "\5\1\1\11\11\1\2\11\2\1\1\0\1\11\3\0"+
    "\11\1\2\0\1\11\11\1\1\0\11\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[79];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */

	public static List<Symbol> tokens(Reader input) throws IOException {
		Lexer lexer = new Lexer(input);
		List<Symbol> result = new ArrayList<Symbol>();
		for (Symbol token = lexer.next_token(); token.sym != sym.EOF; token = lexer.next_token()) {
			result.add(token);
		}
		return result;
	}

	public static void main(String[] args) throws IOException {
		Lexer lexer;
		if (args.length < 1) args = new String[]{ "" };
		for (int i = 0; i < args.length; ++i) {
			lexer = new Lexer(new InputStreamReader(args[i].length() > 0 ? new FileInputStream(args[i]) : System.in, "UTF8"));
			System.out.println(args[i] +":");
			for (Symbol token = lexer.next_token(); token.sym != sym.EOF; token = lexer.next_token()) {
				System.out.println("\t#"+ token.sym +" "+ token.value);
			}
		}
	}



  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Lexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 162) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return new java_cup.runtime.Symbol(sym.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { return new Symbol(error, yyline, yycolumn, "Unexpected input <"+ yytext() +">!");
            }
          case 30: break;
          case 2: 
            { return new Symbol(EXCLAMATION_MARK, yyline, yycolumn, yytext());
            }
          case 31: break;
          case 3: 
            { return new Symbol(LEFT_PARENTHESIS, yyline, yycolumn, yytext());
            }
          case 32: break;
          case 4: 
            { return new Symbol(RIGHT_PARENTHESIS, yyline, yycolumn, yytext());
            }
          case 33: break;
          case 5: 
            { String $1 = yytext(); String $0;
	  $0 = $1;
	  return new Symbol(ID, yyline, yycolumn, $0);
            }
          case 34: break;
          case 6: 
            { return new Symbol(ASTERISK, yyline, yycolumn, yytext());
            }
          case 35: break;
          case 7: 
            { return new Symbol(PLUS_SIGN, yyline, yycolumn, yytext());
            }
          case 36: break;
          case 8: 
            { return new Symbol(HYPHEN_MINUS, yyline, yycolumn, yytext());
            }
          case 37: break;
          case 9: 
            { return new Symbol(SEMICOLON, yyline, yycolumn, yytext());
            }
          case 38: break;
          case 10: 
            { return new Symbol(EQUALS_SIGN, yyline, yycolumn, yytext());
            }
          case 39: break;
          case 11: 
            { return new Symbol(LEFT_CURLY_BRACKET, yyline, yycolumn, yytext());
            }
          case 40: break;
          case 12: 
            { return new Symbol(RIGHT_CURLY_BRACKET, yyline, yycolumn, yytext());
            }
          case 41: break;
          case 13: 
            { String $1 = yytext(); Double $0 = Double.parseDouble($1);
	  return new Symbol(NUM, yyline, yycolumn, $0);
            }
          case 42: break;
          case 14: 
            { /* Ignore */
            }
          case 43: break;
          case 15: 
            { return new Symbol(DOUBLE_AMPERSAND, yyline, yycolumn, yytext());
            }
          case 44: break;
          case 16: 
            { return new Symbol(IF, yyline, yycolumn, yytext());
            }
          case 45: break;
          case 17: 
            { return new Symbol(DO, yyline, yycolumn, yytext());
            }
          case 46: break;
          case 18: 
            { return new Symbol(LESS_THAN_OR_EQUAL, yyline, yycolumn, yytext());
            }
          case 47: break;
          case 19: 
            { return new Symbol(DOUBLE_EQUALS_SIGN, yyline, yycolumn, yytext());
            }
          case 48: break;
          case 20: 
            { String $1 = yytext();
	  $1 = $1.substring(1,$1.length()-1);
	  return new Symbol(STR, yyline, yycolumn, $1);
            }
          case 49: break;
          case 21: 
            { return new Symbol(TRUE, yyline, yycolumn, yytext());
            }
          case 50: break;
          case 22: 
            { return new Symbol(THEN, yyline, yycolumn, yytext());
            }
          case 51: break;
          case 23: 
            { return new Symbol(ELSE, yyline, yycolumn, yytext());
            }
          case 52: break;
          case 24: 
            { return new Symbol(SKIP, yyline, yycolumn, yytext());
            }
          case 53: break;
          case 25: 
            { return new Symbol(PRINT, yyline, yycolumn, yytext());
            }
          case 54: break;
          case 26: 
            { return new Symbol(FALSE, yyline, yycolumn, yytext());
            }
          case 55: break;
          case 27: 
            { return new Symbol(WHILE, yyline, yycolumn, yytext());
            }
          case 56: break;
          case 28: 
            { return new Symbol(LENGTH, yyline, yycolumn, yytext());
            }
          case 57: break;
          case 29: 
            { return new Symbol(DEFINED, yyline, yycolumn, yytext());
            }
          case 58: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
